### ISSUE TITLE
Planned Features

### ISSUE THREAD

**Issue by m1h43l** [sitemule/ILEvator#1]
This is a list of possible features for this project and may or may not be part of a release of the project. Even if they are implemented they don't have to be part of the first release.

Planned Features
- native ILE service program
- programmable HTTP client
- developer-friendly API
- well documented (ILEDocs)
- unit tested (RPGUnit)
- standards compliant
- authentication support (Basic Auth , OAuth 2.0 ( clientId+clientSecret , certificate , x.509, see Keycloak Admin Web Console-> Client -> Credentials ) )
- SSL support
- self-signed certificate support (string, stream file, keystore file object)
- reentrant and thread safe
- forms support
- multipart support ( set as request/response handler )
- trace/debug support (job log , stream file)
- minimum OS version 7.3
- minimum TR ?
- streaming support
- content negotiation ( dynamic translation from correct charset (see Content-Type HTTP header) to native CCSID )
- custom user-defined request handler
- custom user-defined response handler
- automatic retry ( x times) on not successful request
- handling of HTTP status 304 (keeping a previous response in memory)
- websocket support
- support all common HTTP methods (GET , HEAD , POST , PUT , DELETE , PATCH , OPTIONS )
- includes for target languages RPG and C
- easy installable via iPKG
- other protocols: FTP, SFTP

**Comment by m1h43l** [comment]
I think we can tick off almost all of the features. For not implemented features there will be extra tickets if needed.

**Comment by NielsLiisberg** [comment]
Actually "minimum OS version 7.2" as long as extended support for
the version of the OS is offered by IBM
