### ISSUE TITLE
gmake error on CCSID 37 machine - CPD0043: Keyword TGTCCSID not valid for this command.

### ISSUE THREAD

**Issue by richardschoen** [sitemule/ILEvator#36]
Get the following errors:
```
system -i "CRTRPGMOD MODULE(ILEVATOR/api) SRCSTMF('src/api.rpgmod') OUTPUT(*NONE) OPTION(*NOUNREF *SRCSTMT) STGMDL(*INHERIT) INCDIR('headers' 'ext/headers') DBGVIEW(*LIST) TGTRLS(*CURRENT) DEFINE(RPG_HAS_OVERLOAD) TGTCCSID(*JOB)"
CPD0043: Keyword TGTCCSID not valid for this command.
CPF0006: Errors occurred in command.
gmake: *** [makefile:95: api.rpgmod] Error 255
```

Do I need to plug in my specific CCSID of 37 or use 1208 ?

**Comment by richardschoen** [comment]
Appears to be V7R3 related. Not sure if this is working in the make file
```
## OS version dependent defines
OS_VERSION=$(shell uname -v).$(shell uname -r)
ifeq ($(shell expr $(OS_VERSION) \>= 7.3), 1)
DEFINE=RPG_HAS_OVERLOAD
TGTCCSID=TGTCCSID($(TARGET_CCSID))
endif
```

**Comment by m1h43l** [comment]
> Appears to be V7R3 related. Not sure if this is working in the make file
> 
> ```
> ## OS version dependent defines
> OS_VERSION=$(shell uname -v).$(shell uname -r)
> ifeq ($(shell expr $(OS_VERSION) \>= 7.3), 1)
> DEFINE=RPG_HAS_OVERLOAD
> TGTCCSID=TGTCCSID($(TARGET_CCSID))
> endif
> ```

But that would mean TGTCCSID will be evaluated depending on the current machine and evaluates wrong if you build on 7.4 for 7.3.

**Comment by m1h43l** [comment]
I would prefer a check on the target release version and do it like here: https://unix.stackexchange.com/questions/375405/one-line-condition-check-in-makefile
