### ISSUE TITLE
Memory leak in iv_request_toStream

### ISSUE THREAD

**Issue by m1h43l** [sitemule/ILEvator#41]
Both testcases for the toStream procedures are both leaking memory, see REQUESTUT. About 11kb.

**Comment by NielsLiisberg** [comment]
It is more general - look at issue #42 to give a hint

**Comment by m1h43l** [comment]
I started with adding the check for memory leak with `teraspace_leak` in the unit tests and started with the most obvious: request.rpgmod -> requestut. But that module was all good except the streaming stuff.

Next will be the integration tests. I think after that we will have a good overview where the memory leaks occur.

**Comment by NielsLiisberg** [comment]
Look at the "auth" and "proxy" my guess it's around that. Example IVEX019
has the issue, but can be hard to test without an installation of BlueNote
on your system.

The proxy in the example can be used however - and is set up for that
particular purpose.

.
