### ISSUE TITLE
Proxy port issue

### ISSUE THREAD

**Issue by NielsLiisberg** [sitemule/ILEvator#46]
I am testing ILEvator right now, and something goes wrong with the determination of the port of the proxy.

My proxyserver is proxy.abc.local:8080,  but the iv_url_parse stores 80 in url.port, because no proxy is determined.

**Comment by jenschurchill** [comment]
Would the correct way to fix this not be to introduce a proxy_url, equal to url, and store all proxy related information in there? Then use it when use of a proxy is enabled, instead of copying url back and forth? - When using a proxy, it still has to be handed the correct content of url anyway.

**Comment by NielsLiisberg** [comment]
I 100% agree -  however, the current implementation has "forgotten" to reimplement the "opaque" proxy feature ( opposite the transparent CONNECT that works great) while converting the code from C to RPGLE. I am looking at it right now ...

**Comment by m1h43l** [comment]
Proxy support was not on the list of planned features, see #1 .
