### ISSUE TITLE
Noise in joblog

### ISSUE THREAD

**Issue by NielsLiisberg** [sitemule/ILEvator#47]
This message occurs in the joblog. Could that be removed? 

Could not set TLS version: 703: The enumeration for the attribute is not valid., No such path or directory..)

**Comment by m1h43l** [comment]
The output is now only in debug mode.

But I had some trouble getting the numbers into the output message. I had to convert them to a string.
 I think it has something to do with passing the parameters to an RPG module and then again to a C module.
